### ISSUE TITLE
Example of multiple stats repos in same workflow action

### ISSUE THREAD

**Issue by egil** [jgehrcke/github-repo-stats#18]
First of, thanks for an awesome project. Exactly what I needed.

I wanted to share a trick to easily collect stats from multiple repositories in a single workflow. The basic trick is to use a matrix strategy over the stats projects. To make sure that there are no commit conflicts, I've set the `max-parallel` property to 1:

```yaml
name: update-stats
concurrency: 'update-stats'

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "* 23 * * *"
    
  workflow_dispatch: # Allow for running this manually.
  
jobs:
  update-stats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['bob/nice-project', 'alice/also-nice-project']
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.1.0
        with:
          # Define the stats repository (the repo to fetch
          # stats for and to generate the report for).
          # Remove the parameter when the stats repository
          # and the data repository are the same.
          repository: ${{ matrix.statsRepo }}
          # Set a GitHub API token that can read the stats
          # repository, and that can push to the data
          # repository (which this workflow file lives in),
          # to store data and the report files.
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}  
          # Data branch: Branch to push data to (in the data repo).
          databranch: main
```

Thanks again!
