### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by olets** [jgehrcke/github-repo-stats#8]
This is awesome! The world needs this tool!

---

I'm getting this error:

```
210328-00:04:19.208 INFO: leave early: no data for entity of type referrer
210328-00:04:19.208 INFO: cmn_ename_prefix: 
Traceback (most recent call last):
  File "/analyze.py", line 1398, in <module>
    main()
  File "/analyze.py", line 116, in main
    analyse_top_x_snapshots("referrer")
  File "/analyze.py", line 493, in analyse_top_x_snapshots
    del ename
UnboundLocalError: local variable 'ename' referenced before assignment
+ ANALYZE_ECODE=1
error: analyze.py returned with code 1 -- exit.
+ set -e
+ set +x
```

New to Actions so this might be my fault! This is what I did:

1. Created a new personal access token with `repo` privileges
1. Created a new private data repo
1. In that, created `.github/workflows/github-repo-stats.yml`

    ```yaml
    on:
      schedule:
        # Run this once per day (hours in UTC time zone).
        # Towards the end of the day for keeping the last
        # data point meaningful.
        - cron: "* 23 * * *"
      workflow_dispatch: # Allow for running this manually.

    jobs:
      j1:
        name: github-repo-stats
        runs-on: ubuntu-latest
        steps:
          - name: zsh-abbr-stats
            uses: jgehrcke/github-repo-stats@HEAD
            with:
              # Define the target repository, the repo to fetch
              # stats for and to generate the report for.
              # Leave this undefined when stats repository
              # and data repository should be the same.
              repository: olets/zsh-test-runner
              # Required token privileges: Can read the target
              # repo, and can push to the repository this
              # workflow file lives in (to store data and
              # the report files).
              ghtoken: ${{ secrets.ghrs_github_api_token }}
    ```
1. In the data repo's Actions, ran the action

This is a repo (https://github.com/olets/zsh-test-runner) that has had no traffic from anyone except me, and has no stars.

The same steps (with a duplicate yaml file) worked for an established repo (https://github.com/olets/zsh-abbr)
